codecov:
  branch: master
comment:
  layout: "header, changes, diff, sunburst"
coverage:
  ignore:
  - Pods/.*
  - Applications/Xcode.app/.*
  - vendor/.*
  - Carthage/.*
  - .*Tests.m
  - .*Tests.swift
  - '# Add the folders containing your unit tests'
  - '# This ensures any test utility classes you create are also ignored'
  - Demo/Tests/*
  - Demo/Pods/*
  - Demo/Build/*
  status:
    patch: false
notify:
  webhook:
    default:
      url: https://codecov.io/webhooks/github
